package main

// Sprite animation: a coin spins in place on a timer while you move it with the
// D-pad. A strip is a horizontal row of 16px frames in the sprite sheet;
// animate_object walks the object's source cell across them.
//
//   odin run examples/anim       # from the repo root; writes anim.gtr
//
// The sheet (examples/anim/coin.gtg.deflate) is a 4-frame spinning-coin strip at
// sheet row 0: full circle, narrower, edge-on, narrower. It's generated by
// make_coin.ps1 in this folder, into the same raw-DEFLATE format inflate_asset
// expects. Swap in your own strip and set FRAMES/PERIOD to match.

import gt "../../gametank"

BASE   :: u8(0)         // the strip starts at sheet X=0
FRAMES :: u8(4)         // 4 spin frames (cells at X = 0, 16, 32, 48)
PERIOD :: u8(8)         // advance one frame every 8 game-frames (~7.5/sec)
MAX    :: u8(128 - 16)

input, anim: gt.Var

setup :: proc(p: ^gt.Program) {
	gt.blob_file(p, "coin", "examples/anim/coin.gtg.deflate")
	gt.inflate_asset(p, "coin")
	gt.set_object(p, 0, 56, 56, BASE, 0)   // one object, starting on frame 0
	input = gt.alloc_var(p)
	anim  = gt.alloc_var(p)
	gt.timer_set(p, anim, PERIOD)          // arm the animation timer
}

frame :: proc(p: ^gt.Program) {
	in8 := u8(input.addr)
	gt.read_gamepad1(p, in8)
	gt.move_dec(p, in8, gt.PAD_UP,    gt.OBJ_Y + 0, 0)
	gt.move_inc(p, in8, gt.PAD_DOWN,  gt.OBJ_Y + 0, MAX)
	gt.move_dec(p, in8, gt.PAD_LEFT,  gt.OBJ_X + 0, 0)
	gt.move_inc(p, in8, gt.PAD_RIGHT, gt.OBJ_X + 0, MAX)
	gt.animate_object(p, 0, anim, BASE, FRAMES, PERIOD)
	gt.draw_objects(p, 1)
}

main :: proc() {
	gt.build_game(
		gt.Config{size = .K8, out = "anim.gtr", inflate = true},
		gt.Game{
			bg    = gt.color(gt.HUE_INDIGO, gt.SAT_MORE, 1),
			setup = setup,
			frame = frame,
		},
	)
}
